spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog-engine
    username: root
    password: mysql
    initialization-mode: always
  jpa:
    generate-dll: flase
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: m63336072@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

GeneralInfo:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 666-44-55
  email: mail@mail.ru
  copyright: Дмитрий Сергеев
  copyrightFrom: 2005