spring.datasource.url: jdbc:mysql://localhost:3306/blog-engine
spring.datasource.username: root
spring.datasource.password: mysql
spring.jpa.generate-dll: false
spring.jpa.hibernate.ddl-auto: validate
spring.jpa.show-sql: false