spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog-engine?useLegacyDatetimeCode=false
#    url: jdbc:mysql://localhost:3306/blog-engine?serverTimezone=UTC&useLegacyDatetimeCode=false
#    url: jdbc:mysql://localhost:3306/blog-engine
    username: root
    password: mysql
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    generate-dll: flase
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: m63336072@gmail.com
    password: 1234567890
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    serialization:
      fail-on-empty-beans: false
GeneralInfo:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 666-44-55
  email: mail@mail.ru
  copyright: Дмитрий Сергеев
  copyrightFrom: 2005

logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE

