spring.datasource.url: jdbc:mysql://localhost:3306/blog-engine
spring.datasource.username: root
spring.datasource.password: mysql
spring.jpa.generate-dll: false
spring.jpa.hibernate.ddl-auto: validate
spring.jpa.show-sql: false

GeneralInfo:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 666-44-55
  email: mail@mail.ru
  copyright: Дмитрий Сергеев
  copyrightFrom: 2005